// Code generated by Slice Machine. DO NOT EDIT.

import Accordeon from './Accordeon/index.svelte';
import Cards from './Cards/index.svelte';
import Cta from './Cta/index.svelte';
import Headline from './Headline/index.svelte';
import Hero from './Hero/index.svelte';
import Highlights from './Highlights/index.svelte';
import Logos from './Logos/index.svelte';
import SlidingCards from './SlidingCards/index.svelte';
import Text from './Text/index.svelte';

export const components = {
	accordeon: Accordeon,
	cards: Cards,
	cta: Cta,
	headline: Headline,
	hero: Hero,
	highlights: Highlights,
	logos: Logos,
	sliding_cards: SlidingCards,
	text: Text
};
