// Code generated by Slice Machine. DO NOT EDIT.

import Accordeon from './Accordeon/index.svelte';
import Blank from './Blank/index.svelte';
import Cards from './Cards/index.svelte';
import Cta from './Cta/index.svelte';
import Gallery from './Gallery/index.svelte';
import Grid from './Grid/index.svelte';
import Headline from './Headline/index.svelte';
import Hero from './Hero/index.svelte';
import HeroFade from './HeroFade/index.svelte';
import Highlights from './Highlights/index.svelte';
import LeftRight from './LeftRight/index.svelte';
import LeftRightSlider from './LeftRightSlider/index.svelte';
import Logos from './Logos/index.svelte';
import Media from './Media/index.svelte';
import Pricing from './Pricing/index.svelte';
import SlidingCards from './SlidingCards/index.svelte';
import Text from './Text/index.svelte';

export const components = {
	accordeon: Accordeon,
	blank: Blank,
	cards: Cards,
	cta: Cta,
	gallery: Gallery,
	grid: Grid,
	headline: Headline,
	hero: Hero,
	hero_fade: HeroFade,
	highlights: Highlights,
	left_right: LeftRight,
	left_right_slider: LeftRightSlider,
	logos: Logos,
	media: Media,
	pricing: Pricing,
	sliding_cards: SlidingCards,
	text: Text
};
