// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Links field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.links
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	links: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * Links field in *Header*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.links
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	links: prismic.Repeatable<prismic.LinkField>;

	/**
	 * Button field in *Header*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.button
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.LinkField;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HeaderDocumentData>,
	'header',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| GallerySlice
	| BlankSlice
	| HeroFadeSlice
	| MediaSlice
	| LeftRightSlice
	| AccordeonSlice
	| HeroSlice
	| LogosSlice
	| HeadlineSlice
	| HighlightsSlice
	| CtaSlice
	| SlidingCardsSlice
	| TextSlice
	| CardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

export type AllDocumentTypes = FooterDocument | HeaderDocument | PageDocument;

/**
 * Item in *Accordeon → Default → Primary → Items*
 */
export interface AccordeonSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Headline field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Accordeon → Default → Primary*
 */
export interface AccordeonSliceDefaultPrimary {
	/**
	 * hash field in *Accordeon → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Accordeon → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *Accordeon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<AccordeonSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Accordeon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordeonSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AccordeonSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Accordeon*
 */
type AccordeonSliceVariation = AccordeonSliceDefault;

/**
 * Accordeon Shared Slice
 *
 * - **API ID**: `accordeon`
 * - **Description**: Accordeon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordeonSlice = prismic.SharedSlice<'accordeon', AccordeonSliceVariation>;

/**
 * Primary content in *Blank → Default → Primary*
 */
export interface BlankSliceDefaultPrimary {
	/**
	 * Selector field in *Blank → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blank.default.primary.selector
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	selector: prismic.SelectField<'xxl' | 'xl' | 'l' | 'm' | 's'>;
}

/**
 * Default variation for Blank Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlankSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BlankSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Blank*
 */
type BlankSliceVariation = BlankSliceDefault;

/**
 * Blank Shared Slice
 *
 * - **API ID**: `blank`
 * - **Description**: Blank
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlankSlice = prismic.SharedSlice<'blank', BlankSliceVariation>;

/**
 * Item in *Cards → Default → Primary → Items*
 */
export interface CardsSliceDefaultPrimaryItemsItem {
	/**
	 * Headline field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
	/**
	 * hash field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<'cards', CardsSliceVariation>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
	/**
	 * hash field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Button field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.LinkField;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CtaSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<'cta', CtaSliceVariation>;

/**
 * Item in *Gallery → Default → Primary → Items*
 */
export interface GallerySliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Controlled field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: gallery.default.primary.items[].controlled
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	controlled: prismic.BooleanField;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
	/**
	 * Columns field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 2
	 * - **API ID Path**: gallery.default.primary.columns
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	columns: prismic.SelectField<'2' | '3' | '4', 'filled'>;

	/**
	 * Size field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: gallery.default.primary.size
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	size: prismic.BooleanField;

	/**
	 * Items field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<GallerySliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GallerySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<'gallery', GallerySliceVariation>;

/**
 * Primary content in *Headline → Default → Primary*
 */
export interface HeadlineSliceDefaultPrimary {
	/**
	 * hash field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.RichTextField;

	/**
	 * Text field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Big field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: headline.default.primary.big
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	big: prismic.BooleanField;
}

/**
 * Default variation for Headline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeadlineSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Headline*
 */
type HeadlineSliceVariation = HeadlineSliceDefault;

/**
 * Headline Shared Slice
 *
 * - **API ID**: `headline`
 * - **Description**: Headline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSlice = prismic.SharedSlice<'headline', HeadlineSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Items*
 */
export interface HeroSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Link field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * hash field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Items field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *HeroFade → Default → Primary → Items*
 */
export interface HeroFadeSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Link field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *HeroFade → Default → Primary*
 */
export interface HeroFadeSliceDefaultPrimary {
	/**
	 * hash field in *HeroFade → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Items field in *HeroFade → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<HeroFadeSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for HeroFade Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFadeSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroFadeSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeroFade*
 */
type HeroFadeSliceVariation = HeroFadeSliceDefault;

/**
 * HeroFade Shared Slice
 *
 * - **API ID**: `hero_fade`
 * - **Description**: HeroFade
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFadeSlice = prismic.SharedSlice<'hero_fade', HeroFadeSliceVariation>;

/**
 * Item in *Highlights → Default → Primary → Items*
 */
export interface HighlightsSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Highlights → Default → Primary*
 */
export interface HighlightsSliceDefaultPrimary {
	/**
	 * hash field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<HighlightsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Highlights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HighlightsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Highlights*
 */
type HighlightsSliceVariation = HighlightsSliceDefault;

/**
 * Highlights Shared Slice
 *
 * - **API ID**: `highlights`
 * - **Description**: Highlights
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightsSlice = prismic.SharedSlice<'highlights', HighlightsSliceVariation>;

/**
 * Primary content in *LeftRight → Default → Primary*
 */
export interface LeftRightSliceDefaultPrimary {
	/**
	 * hash field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Switched field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: left_right.default.primary.switched
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	switched: prismic.BooleanField;

	/**
	 * Image field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Headline field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Default variation for LeftRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftRightSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LeftRightSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *LeftRight*
 */
type LeftRightSliceVariation = LeftRightSliceDefault;

/**
 * LeftRight Shared Slice
 *
 * - **API ID**: `left_right`
 * - **Description**: LeftRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftRightSlice = prismic.SharedSlice<'left_right', LeftRightSliceVariation>;

/**
 * Item in *Logos → Default → Primary → Items*
 */
export interface LogosSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Logos → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Logos → Default → Primary*
 */
export interface LogosSliceDefaultPrimary {
	/**
	 * hash field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<LogosSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LogosSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<'logos', LogosSliceVariation>;

/**
 * Primary content in *Media → Default → Primary*
 */
export interface MediaSliceDefaultPrimary {
	/**
	 * Hash field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Image field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Style field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'inline' | 'big' | 'full' | 'logo'>;

	/**
	 * Controlled field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: media.default.primary.controlled
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	controlled: prismic.BooleanField;
}

/**
 * Default variation for Media Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MediaSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Media*
 */
type MediaSliceVariation = MediaSliceDefault;

/**
 * Media Shared Slice
 *
 * - **API ID**: `media`
 * - **Description**: Media
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSlice = prismic.SharedSlice<'media', MediaSliceVariation>;

/**
 * Item in *SlidingCards → Default → Primary → Items*
 */
export interface SlidingCardsSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Headline field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *SlidingCards → Default → Primary*
 */
export interface SlidingCardsSliceDefaultPrimary {
	/**
	 * hash field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<SlidingCardsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for SlidingCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidingCardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SlidingCardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *SlidingCards*
 */
type SlidingCardsSliceVariation = SlidingCardsSliceDefault;

/**
 * SlidingCards Shared Slice
 *
 * - **API ID**: `sliding_cards`
 * - **Description**: SlidingCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidingCardsSlice = prismic.SharedSlice<'sliding_cards', SlidingCardsSliceVariation>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
	/**
	 * hash field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Centered field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: text.default.primary.centered
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	centered: prismic.BooleanField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			HeaderDocument,
			HeaderDocumentData,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			AllDocumentTypes,
			AccordeonSlice,
			AccordeonSliceDefaultPrimaryItemsItem,
			AccordeonSliceDefaultPrimary,
			AccordeonSliceVariation,
			AccordeonSliceDefault,
			BlankSlice,
			BlankSliceDefaultPrimary,
			BlankSliceVariation,
			BlankSliceDefault,
			CardsSlice,
			CardsSliceDefaultPrimaryItemsItem,
			CardsSliceDefaultPrimary,
			CardsSliceVariation,
			CardsSliceDefault,
			CtaSlice,
			CtaSliceDefaultPrimary,
			CtaSliceVariation,
			CtaSliceDefault,
			GallerySlice,
			GallerySliceDefaultPrimaryItemsItem,
			GallerySliceDefaultPrimary,
			GallerySliceVariation,
			GallerySliceDefault,
			HeadlineSlice,
			HeadlineSliceDefaultPrimary,
			HeadlineSliceVariation,
			HeadlineSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimaryItemsItem,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroFadeSlice,
			HeroFadeSliceDefaultPrimaryItemsItem,
			HeroFadeSliceDefaultPrimary,
			HeroFadeSliceVariation,
			HeroFadeSliceDefault,
			HighlightsSlice,
			HighlightsSliceDefaultPrimaryItemsItem,
			HighlightsSliceDefaultPrimary,
			HighlightsSliceVariation,
			HighlightsSliceDefault,
			LeftRightSlice,
			LeftRightSliceDefaultPrimary,
			LeftRightSliceVariation,
			LeftRightSliceDefault,
			LogosSlice,
			LogosSliceDefaultPrimaryItemsItem,
			LogosSliceDefaultPrimary,
			LogosSliceVariation,
			LogosSliceDefault,
			MediaSlice,
			MediaSliceDefaultPrimary,
			MediaSliceVariation,
			MediaSliceDefault,
			SlidingCardsSlice,
			SlidingCardsSliceDefaultPrimaryItemsItem,
			SlidingCardsSliceDefaultPrimary,
			SlidingCardsSliceVariation,
			SlidingCardsSliceDefault,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceVariation,
			TextSliceDefault
		};
	}
}
