// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from '@prismicio/client';

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Links field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.links
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	links: prismic.Repeatable<prismic.LinkField>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<FooterDocumentData>,
	'footer',
	Lang
>;

/**
 * Item in *General → Testimonial*
 */
export interface GeneralDocumentDataTestimonialItem {
	/**
	 * Position field in *General → Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial[].position
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	position: prismic.KeyTextField;

	/**
	 * Name field in *General → Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Company field in *General → Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial[].company
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	company: prismic.KeyTextField;

	/**
	 * Quote field in *General → Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial[].quote
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	quote: prismic.KeyTextField;

	/**
	 * Image field in *General → Testimonial*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Item in *General → Logos*
 */
export interface GeneralDocumentDataLogosItem {
	/**
	 * Image field in *General → Logos*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.logos[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Content for General documents
 */
interface GeneralDocumentData {
	/**
	 * Testimonial field in *General*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	testimonial: prismic.GroupField<Simplify<GeneralDocumentDataTestimonialItem>>;

	/**
	 * Testimonial Headline field in *General*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial_headline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	testimonial_headline: prismic.KeyTextField;

	/**
	 * Testimonial Subheadline field in *General*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.testimonial_subheadline
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	testimonial_subheadline: prismic.KeyTextField;

	/**
	 * CTA Header field in *General*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.cta_header
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_header: prismic.KeyTextField;

	/**
	 * CTA Text field in *General*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.cta_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	cta_text: prismic.KeyTextField;

	/**
	 * CTA Link field in *General*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.cta_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	cta_link: prismic.LinkField;

	/**
	 * CTA Image field in *General*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.cta_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	cta_image: prismic.ImageField<never>;

	/**
	 * Logos field in *General*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: general.logos[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	logos: prismic.GroupField<Simplify<GeneralDocumentDataLogosItem>>;
}

/**
 * General document from Prismic
 *
 * - **API ID**: `general`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type GeneralDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<GeneralDocumentData>,
	'general',
	Lang
>;

/**
 * Item in *Header → Nav Top*
 */
export interface HeaderDocumentDataNavTopItem {
	/**
	 * Link field in *Header → Nav Top*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.nav_top[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Anchor field in *Header → Nav Top*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.nav_top[].anchor
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	anchor: prismic.KeyTextField;
}

/**
 * Content for Header documents
 */
interface HeaderDocumentData {
	/**
	 * Button field in *Header*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.button
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.LinkField;

	/**
	 * Nav Top field in *Header*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: header.nav_top[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	nav_top: prismic.GroupField<Simplify<HeaderDocumentDataNavTopItem>>;
}

/**
 * Header document from Prismic
 *
 * - **API ID**: `header`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HeaderDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<
	Simplify<HeaderDocumentData>,
	'header',
	Lang
>;

type NewsArticleDocumentDataSlicesSlice =
	| GridSlice
	| BlankSlice
	| TextSlice
	| SlidingCardsSlice
	| PricingSlice
	| MediaSlice
	| LeftRightSlice
	| LeftRightSliderSlice
	| LogosSlice
	| HighlightsSlice
	| HeroFadeSlice
	| HeroSlice
	| CtaSlice
	| GallerySlice
	| HeadlineSlice
	| CardsSlice
	| AccordeonSlice;

/**
 * Content for News Article documents
 */
interface NewsArticleDocumentData {
	/**
	 * Title field in *News Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_article.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *News Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_article.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * Date field in *News Article*
	 *
	 * - **Field Type**: Date
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_article.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#date
	 */
	date: prismic.DateField;

	/**
	 * Image field in *News Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_article.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *News Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_article.video
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Layout field in *News Article*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1
	 * - **API ID Path**: news_article.layout
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	layout: prismic.SelectField<'1' | '2' | '3', 'filled'>;

	/**
	 * Slice Zone field in *News Article*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_article.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<NewsArticleDocumentDataSlicesSlice> /**
	 * Meta Title field in *News Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: news_article.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *News Article*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: news_article.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *News Article*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news_article.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * News Article document from Prismic
 *
 * - **API ID**: `news_article`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NewsArticleDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<NewsArticleDocumentData>,
	'news_article',
	Lang
>;

type PageDocumentDataSlicesSlice =
	| NewsSlice
	| ExplanationSlice
	| ProjectsSlice
	| LogosAnimatedSlice
	| TestimonialsSlice
	| FeaturedProjectsSlice
	| LatestNewsSlice
	| GridSlice
	| LeftRightSliderSlice
	| PricingSlice
	| GallerySlice
	| BlankSlice
	| HeroFadeSlice
	| MediaSlice
	| LeftRightSlice
	| AccordeonSlice
	| HeroSlice
	| LogosSlice
	| HeadlineSlice
	| HighlightsSlice
	| CtaSlice
	| SlidingCardsSlice
	| TextSlice
	| CardsSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Title field in *Page*
	 *
	 * - **Field Type**: Title
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	title: prismic.TitleField;

	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
	 * Meta Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<PageDocumentData>,
	'page',
	Lang
>;

/**
 * Item in *Project → Infos*
 */
export interface ProjectDocumentDataInfosItem {
	/**
	 * Label field in *Project → Infos*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.infos[].label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Text field in *Project → Infos*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.infos[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;
}

type ProjectDocumentDataSlicesSlice =
	| ExplanationSlice
	| TestimonialsSlice
	| FeaturedProjectsSlice
	| LogosAnimatedSlice
	| ProjectsSlice
	| LatestNewsSlice
	| CtaSlice
	| BlankSlice
	| CardsSlice
	| HeadlineSlice
	| LogosSlice
	| SlidingCardsSlice
	| PricingSlice
	| TextSlice
	| LeftRightSliderSlice
	| LeftRightSlice
	| HeroSlice
	| GallerySlice
	| AccordeonSlice
	| MediaSlice
	| HighlightsSlice
	| HeroFadeSlice
	| GridSlice;

/**
 * Content for Project documents
 */
interface ProjectDocumentData {
	/**
	 * Title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	title: prismic.KeyTextField;

	/**
	 * Subtitle field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.subtitle
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	subtitle: prismic.KeyTextField;

	/**
	 * Image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.video
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Layout field in *Project*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 1
	 * - **API ID Path**: project.layout
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	layout: prismic.SelectField<'1' | '2', 'filled'>;

	/**
	 * Infos field in *Project*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.infos[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	infos: prismic.GroupField<Simplify<ProjectDocumentDataInfosItem>>;

	/**
	 * Slice Zone field in *Project*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/field#slices
	 */
	slices: prismic.SliceZone<ProjectDocumentDataSlicesSlice> /**
	 * Meta Title field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A title of the page used for social media and search engines
	 * - **API ID Path**: project.meta_title
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */;
	meta_title: prismic.KeyTextField;

	/**
	 * Meta Description field in *Project*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: A brief summary of the page
	 * - **API ID Path**: project.meta_description
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Meta Image field in *Project*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: project.meta_image
	 * - **Tab**: SEO & Metadata
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	meta_image: prismic.ImageField<never>;
}

/**
 * Project document from Prismic
 *
 * - **API ID**: `project`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ProjectDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<
	Simplify<ProjectDocumentData>,
	'project',
	Lang
>;

export type AllDocumentTypes =
	| FooterDocument
	| GeneralDocument
	| HeaderDocument
	| NewsArticleDocument
	| PageDocument
	| ProjectDocument;

/**
 * Item in *Accordeon → Default → Primary → Items*
 */
export interface AccordeonSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Headline field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Accordeon → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Accordeon → Default → Primary*
 */
export interface AccordeonSliceDefaultPrimary {
	/**
	 * Deactivated field in *Accordeon → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: accordeon.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Accordeon → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Accordeon → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *Accordeon → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: accordeon.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<AccordeonSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Accordeon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordeonSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<AccordeonSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Accordeon*
 */
type AccordeonSliceVariation = AccordeonSliceDefault;

/**
 * Accordeon Shared Slice
 *
 * - **API ID**: `accordeon`
 * - **Description**: Accordeon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AccordeonSlice = prismic.SharedSlice<'accordeon', AccordeonSliceVariation>;

/**
 * Primary content in *Blank → Default → Primary*
 */
export interface BlankSliceDefaultPrimary {
	/**
	 * Deactivated field in *Blank → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: blank.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * Selector field in *Blank → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blank.default.primary.selector
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	selector: prismic.SelectField<'xxl' | 'xl' | 'l' | 'm' | 's'>;
}

/**
 * Default variation for Blank Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlankSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<BlankSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Blank*
 */
type BlankSliceVariation = BlankSliceDefault;

/**
 * Blank Shared Slice
 *
 * - **API ID**: `blank`
 * - **Description**: Blank
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlankSlice = prismic.SharedSlice<'blank', BlankSliceVariation>;

/**
 * Item in *Cards → Default → Primary → Items*
 */
export interface CardsSliceDefaultPrimaryItemsItem {
	/**
	 * Headline field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.RichTextField;

	/**
	 * Text field in *Cards → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Primary content in *Cards → Default → Primary*
 */
export interface CardsSliceDefaultPrimary {
	/**
	 * Deactivated field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cards.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *Cards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cards.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<CardsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Cards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Cards*
 */
type CardsSliceVariation = CardsSliceDefault;

/**
 * Cards Shared Slice
 *
 * - **API ID**: `cards`
 * - **Description**: Cards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CardsSlice = prismic.SharedSlice<'cards', CardsSliceVariation>;

/**
 * Primary content in *Cta → Default → Primary*
 */
export interface CtaSliceDefaultPrimary {
	/**
	 * Deactivated field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: cta.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Button field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.LinkField;

	/**
	 * Image field in *Cta → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for Cta Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<CtaSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Cta*
 */
type CtaSliceVariation = CtaSliceDefault;

/**
 * Cta Shared Slice
 *
 * - **API ID**: `cta`
 * - **Description**: Cta
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CtaSlice = prismic.SharedSlice<'cta', CtaSliceVariation>;

/**
 * Primary content in *Explanation → Default → Primary*
 */
export interface ExplanationSliceDefaultPrimary {
	/**
	 * Label field in *Explanation → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: explanation.default.primary.label
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	label: prismic.KeyTextField;

	/**
	 * Text field in *Explanation → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: explanation.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;
}

/**
 * Default variation for Explanation Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExplanationSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ExplanationSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Explanation*
 */
type ExplanationSliceVariation = ExplanationSliceDefault;

/**
 * Explanation Shared Slice
 *
 * - **API ID**: `explanation`
 * - **Description**: Explanation
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ExplanationSlice = prismic.SharedSlice<'explanation', ExplanationSliceVariation>;

/**
 * Item in *FeaturedProjects → Default → Primary → Items*
 */
export interface FeaturedProjectsSliceDefaultPrimaryItemsItem {
	/**
	 * Project field in *FeaturedProjects → Default → Primary → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_projects.default.primary.items[].project
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project: prismic.ContentRelationshipField<'project'>;
}

/**
 * Primary content in *FeaturedProjects → Default → Primary*
 */
export interface FeaturedProjectsSliceDefaultPrimary {
	/**
	 * Style field in *FeaturedProjects → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: normal
	 * - **API ID Path**: featured_projects.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'normal' | 'fullscreen', 'filled'>;

	/**
	 * Items field in *FeaturedProjects → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: featured_projects.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<FeaturedProjectsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for FeaturedProjects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<FeaturedProjectsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *FeaturedProjects*
 */
type FeaturedProjectsSliceVariation = FeaturedProjectsSliceDefault;

/**
 * FeaturedProjects Shared Slice
 *
 * - **API ID**: `featured_projects`
 * - **Description**: FeaturedProjects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedProjectsSlice = prismic.SharedSlice<
	'featured_projects',
	FeaturedProjectsSliceVariation
>;

/**
 * Item in *Gallery → Default → Primary → Items*
 */
export interface GallerySliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Controlled field in *Gallery → Default → Primary → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: gallery.default.primary.items[].controlled
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	controlled: prismic.BooleanField;
}

/**
 * Primary content in *Gallery → Default → Primary*
 */
export interface GallerySliceDefaultPrimary {
	/**
	 * Deactivated field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: gallery.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * Columns field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: 2
	 * - **API ID Path**: gallery.default.primary.columns
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	columns: prismic.SelectField<'2' | '3' | '4' | '1', 'filled'>;

	/**
	 * Size field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: gallery.default.primary.size
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	size: prismic.BooleanField;

	/**
	 * Items field in *Gallery → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: gallery.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<GallerySliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Gallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GallerySliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Gallery*
 */
type GallerySliceVariation = GallerySliceDefault;

/**
 * Gallery Shared Slice
 *
 * - **API ID**: `gallery`
 * - **Description**: Gallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GallerySlice = prismic.SharedSlice<'gallery', GallerySliceVariation>;

/**
 * Item in *Grid → Default → Primary → Items*
 */
export interface GridSliceDefaultPrimaryItemsItem {
	/**
	 * Related field in *Grid → Default → Primary → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: grid.default.primary.items[].related
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	related: prismic.ContentRelationshipField<'news_article' | 'project'>;
}

/**
 * Primary content in *Grid → Default → Primary*
 */
export interface GridSliceDefaultPrimary {
	/**
	 * Headline field in *Grid → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: grid.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *Grid → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: grid.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<GridSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Grid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<GridSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Grid*
 */
type GridSliceVariation = GridSliceDefault;

/**
 * Grid Shared Slice
 *
 * - **API ID**: `grid`
 * - **Description**: Grid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type GridSlice = prismic.SharedSlice<'grid', GridSliceVariation>;

/**
 * Primary content in *Headline → Default → Primary*
 */
export interface HeadlineSliceDefaultPrimary {
	/**
	 * Deactivated field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: headline.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.RichTextField;

	/**
	 * Text field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Button field in *Headline → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: headline.default.primary.button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.LinkField;
}

/**
 * Default variation for Headline Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeadlineSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Headline*
 */
type HeadlineSliceVariation = HeadlineSliceDefault;

/**
 * Headline Shared Slice
 *
 * - **API ID**: `headline`
 * - **Description**: Headline
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeadlineSlice = prismic.SharedSlice<'headline', HeadlineSliceVariation>;

/**
 * Item in *Hero → Default → Primary → Items*
 */
export interface HeroSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Link field in *Hero → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Deactivated field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Style field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: normal
	 * - **API ID Path**: hero.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'normal' | 'fullscreen', 'filled'>;

	/**
	 * Items field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<HeroSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<'hero', HeroSliceVariation>;

/**
 * Item in *HeroFade → Default → Primary → Items*
 */
export interface HeroFadeSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	text: prismic.KeyTextField;

	/**
	 * Link field in *HeroFade → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *HeroFade → Default → Primary*
 */
export interface HeroFadeSliceDefaultPrimary {
	/**
	 * Deactivated field in *HeroFade → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: hero_fade.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *HeroFade → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Items field in *HeroFade → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero_fade.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<HeroFadeSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for HeroFade Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFadeSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HeroFadeSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *HeroFade*
 */
type HeroFadeSliceVariation = HeroFadeSliceDefault;

/**
 * HeroFade Shared Slice
 *
 * - **API ID**: `hero_fade`
 * - **Description**: HeroFade
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroFadeSlice = prismic.SharedSlice<'hero_fade', HeroFadeSliceVariation>;

/**
 * Item in *Highlights → Default → Primary → Items*
 */
export interface HighlightsSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *Highlights → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *Highlights → Default → Primary*
 */
export interface HighlightsSliceDefaultPrimary {
	/**
	 * Deactivated field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: highlights.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Mobile Simple field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: highlights.default.primary.mobile_simple
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	mobile_simple: prismic.BooleanField;

	/**
	 * Items field in *Highlights → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: highlights.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<HighlightsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Highlights Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<HighlightsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Highlights*
 */
type HighlightsSliceVariation = HighlightsSliceDefault;

/**
 * Highlights Shared Slice
 *
 * - **API ID**: `highlights`
 * - **Description**: Highlights
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HighlightsSlice = prismic.SharedSlice<'highlights', HighlightsSliceVariation>;

/**
 * Default variation for LatestNews Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestNewsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Record<string, never>,
	never
>;

/**
 * Slice variation for *LatestNews*
 */
type LatestNewsSliceVariation = LatestNewsSliceDefault;

/**
 * LatestNews Shared Slice
 *
 * - **API ID**: `latest_news`
 * - **Description**: LatestNews
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LatestNewsSlice = prismic.SharedSlice<'latest_news', LatestNewsSliceVariation>;

/**
 * Primary content in *LeftRight → Default → Primary*
 */
export interface LeftRightSliceDefaultPrimary {
	/**
	 * Deactivated field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: left_right.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Switched field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: left_right.default.primary.switched
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	switched: prismic.BooleanField;

	/**
	 * Image field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Headline field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.RichTextField;

	/**
	 * Text field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right.default.primary.link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Big field in *LeftRight → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: left_right.default.primary.big
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	big: prismic.BooleanField;
}

/**
 * Default variation for LeftRight Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftRightSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LeftRightSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *LeftRight*
 */
type LeftRightSliceVariation = LeftRightSliceDefault;

/**
 * LeftRight Shared Slice
 *
 * - **API ID**: `left_right`
 * - **Description**: LeftRight
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftRightSlice = prismic.SharedSlice<'left_right', LeftRightSliceVariation>;

/**
 * Item in *LeftRightSlider → Default → Primary → Items*
 */
export interface LeftRightSliderSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *LeftRightSlider → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *LeftRightSlider → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Headline field in *LeftRightSlider → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.RichTextField;

	/**
	 * Text field in *LeftRightSlider → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Text 2 field in *LeftRightSlider → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.items[].text_2
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text_2: prismic.RichTextField;

	/**
	 * Link field in *LeftRightSlider → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;
}

/**
 * Primary content in *LeftRightSlider → Default → Primary*
 */
export interface LeftRightSliderSliceDefaultPrimary {
	/**
	 * Deactivated field in *LeftRightSlider → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: left_right_slider.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *LeftRightSlider → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *LeftRightSlider → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Mobile Simple field in *LeftRightSlider → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: left_right_slider.default.primary.mobile_simple
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	mobile_simple: prismic.BooleanField;

	/**
	 * Items field in *LeftRightSlider → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: left_right_slider.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<LeftRightSliderSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for LeftRightSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftRightSliderSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LeftRightSliderSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *LeftRightSlider*
 */
type LeftRightSliderSliceVariation = LeftRightSliderSliceDefault;

/**
 * LeftRightSlider Shared Slice
 *
 * - **API ID**: `left_right_slider`
 * - **Description**: LeftRightSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LeftRightSliderSlice = prismic.SharedSlice<
	'left_right_slider',
	LeftRightSliderSliceVariation
>;

/**
 * Item in *Logos → Default → Primary → Items*
 */
export interface LogosSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Logos → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Logos → Default → Primary*
 */
export interface LogosSliceDefaultPrimary {
	/**
	 * Deactivated field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: logos.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Logos in a row field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.logos_in_a_row
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	logos_in_a_row: prismic.NumberField;

	/**
	 * Items field in *Logos → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<LogosSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Logos Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LogosSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Logos*
 */
type LogosSliceVariation = LogosSliceDefault;

/**
 * Logos Shared Slice
 *
 * - **API ID**: `logos`
 * - **Description**: Logos
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosSlice = prismic.SharedSlice<'logos', LogosSliceVariation>;

/**
 * Item in *LogosAnimated → Default → Primary → Items*
 */
export interface LogosAnimatedSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *LogosAnimated → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos_animated.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *LogosAnimated → Default → Primary*
 */
export interface LogosAnimatedSliceDefaultPrimary {
	/**
	 * Headline field in *LogosAnimated → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos_animated.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Items field in *LogosAnimated → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: logos_animated.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<LogosAnimatedSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for LogosAnimated Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosAnimatedSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<LogosAnimatedSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *LogosAnimated*
 */
type LogosAnimatedSliceVariation = LogosAnimatedSliceDefault;

/**
 * LogosAnimated Shared Slice
 *
 * - **API ID**: `logos_animated`
 * - **Description**: LogosAnimated
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type LogosAnimatedSlice = prismic.SharedSlice<'logos_animated', LogosAnimatedSliceVariation>;

/**
 * Item in *Media → Default → Primary → Items*
 */
export interface MediaSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *Media → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Primary content in *Media → Default → Primary*
 */
export interface MediaSliceDefaultPrimary {
	/**
	 * Deactivated field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: media.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * Hash field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Image field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Style field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.style
	 * - **Documentation**: https://prismic.io/docs/field#select
	 */
	style: prismic.SelectField<'inline' | 'big' | 'full' | 'logo'>;

	/**
	 * Controlled field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: media.default.primary.controlled
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	controlled: prismic.BooleanField;

	/**
	 * Items field in *Media → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: media.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<MediaSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Media Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<MediaSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Media*
 */
type MediaSliceVariation = MediaSliceDefault;

/**
 * Media Shared Slice
 *
 * - **API ID**: `media`
 * - **Description**: Media
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaSlice = prismic.SharedSlice<'media', MediaSliceVariation>;

/**
 * Item in *News → Default → Primary → Items*
 */
export interface NewsSliceDefaultPrimaryItemsItem {
	/**
	 * Item field in *News → Default → Primary → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news.default.primary.items[].item
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	item: prismic.ContentRelationshipField<'news_article'>;
}

/**
 * Primary content in *News → Default → Primary*
 */
export interface NewsSliceDefaultPrimary {
	/**
	 * Items field in *News → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: news.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<NewsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for News Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<NewsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *News*
 */
type NewsSliceVariation = NewsSliceDefault;

/**
 * News Shared Slice
 *
 * - **API ID**: `news`
 * - **Description**: News
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsSlice = prismic.SharedSlice<'news', NewsSliceVariation>;

/**
 * Item in *Pricing → Default → Primary → Items*
 */
export interface PricingSliceDefaultPrimaryItemsItem {
	/**
	 * Headline field in *Pricing → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Price field in *Pricing → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.default.primary.items[].price
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	price: prismic.KeyTextField;

	/**
	 * Subheadline field in *Pricing → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.default.primary.items[].subheadline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	subheadline: prismic.RichTextField;

	/**
	 * Text field in *Pricing → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Button field in *Pricing → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.default.primary.items[].button
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	button: prismic.LinkField;

	/**
	 * Info field in *Pricing → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.default.primary.items[].info
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	info: prismic.RichTextField;
}

/**
 * Primary content in *Pricing → Default → Primary*
 */
export interface PricingSliceDefaultPrimary {
	/**
	 * Deactivated field in *Pricing → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: pricing.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * Items field in *Pricing → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: pricing.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<PricingSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Pricing Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<PricingSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Pricing*
 */
type PricingSliceVariation = PricingSliceDefault;

/**
 * Pricing Shared Slice
 *
 * - **API ID**: `pricing`
 * - **Description**: Pricing
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PricingSlice = prismic.SharedSlice<'pricing', PricingSliceVariation>;

/**
 * Item in *Projects → Default → Primary → Items*
 */
export interface ProjectsSliceDefaultPrimaryItemsItem {
	/**
	 * Project field in *Projects → Default → Primary → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.items[].project
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	project: prismic.ContentRelationshipField<'project'>;
}

/**
 * Primary content in *Projects → Default → Primary*
 */
export interface ProjectsSliceDefaultPrimary {
	/**
	 * Items field in *Projects → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: projects.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<ProjectsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Projects Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<ProjectsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Projects*
 */
type ProjectsSliceVariation = ProjectsSliceDefault;

/**
 * Projects Shared Slice
 *
 * - **API ID**: `projects`
 * - **Description**: Projects
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ProjectsSlice = prismic.SharedSlice<'projects', ProjectsSliceVariation>;

/**
 * Item in *SlidingCards → Default → Primary → Items*
 */
export interface SlidingCardsSliceDefaultPrimaryItemsItem {
	/**
	 * Image field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].image
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	image: prismic.ImageField<never>;

	/**
	 * Video field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].video
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	video: prismic.KeyTextField;

	/**
	 * Text field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Link field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].link
	 * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
	 */
	link: prismic.LinkField;

	/**
	 * Headline field in *SlidingCards → Default → Primary → Items*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[].headline
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	headline: prismic.RichTextField;
}

/**
 * Primary content in *SlidingCards → Default → Primary*
 */
export interface SlidingCardsSliceDefaultPrimary {
	/**
	 * Deactivated field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: sliding_cards.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Slider field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: sliding_cards.default.primary.slider
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	slider: prismic.BooleanField;

	/**
	 * Items per row field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items_per_row
	 * - **Documentation**: https://prismic.io/docs/field#number
	 */
	items_per_row: prismic.NumberField;

	/**
	 * Items field in *SlidingCards → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: sliding_cards.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<SlidingCardsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for SlidingCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidingCardsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<SlidingCardsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *SlidingCards*
 */
type SlidingCardsSliceVariation = SlidingCardsSliceDefault;

/**
 * SlidingCards Shared Slice
 *
 * - **API ID**: `sliding_cards`
 * - **Description**: SlidingCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlidingCardsSlice = prismic.SharedSlice<'sliding_cards', SlidingCardsSliceVariation>;

/**
 * Item in *Testimonials → Default → Primary → Items*
 */
export interface TestimonialsSliceDefaultPrimaryItemsItem {
	/**
	 * Portrait field in *Testimonials → Default → Primary → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.items[].portrait
	 * - **Documentation**: https://prismic.io/docs/field#image
	 */
	portrait: prismic.ImageField<never>;

	/**
	 * Name field in *Testimonials → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.items[].name
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	name: prismic.KeyTextField;

	/**
	 * Company field in *Testimonials → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.items[].company
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	company: prismic.KeyTextField;

	/**
	 * Position field in *Testimonials → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.items[].position
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	position: prismic.KeyTextField;

	/**
	 * Quote field in *Testimonials → Default → Primary → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.items[].quote
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	quote: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
	/**
	 * Items field in *Testimonials → Default → Primary*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: testimonials.default.primary.items[]
	 * - **Documentation**: https://prismic.io/docs/field#group
	 */
	items: prismic.GroupField<Simplify<TestimonialsSliceDefaultPrimaryItemsItem>>;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TestimonialsSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<'testimonials', TestimonialsSliceVariation>;

/**
 * Primary content in *Text → Default → Primary*
 */
export interface TextSliceDefaultPrimary {
	/**
	 * Deactivated field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: text.default.primary.deactivated
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	deactivated: prismic.BooleanField;

	/**
	 * hash field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.hash
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	hash: prismic.KeyTextField;

	/**
	 * Headline field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.headline
	 * - **Documentation**: https://prismic.io/docs/field#key-text
	 */
	headline: prismic.KeyTextField;

	/**
	 * Text field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: text.default.primary.text
	 * - **Documentation**: https://prismic.io/docs/field#rich-text-title
	 */
	text: prismic.RichTextField;

	/**
	 * Centered field in *Text → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: text.default.primary.centered
	 * - **Documentation**: https://prismic.io/docs/field#boolean
	 */
	centered: prismic.BooleanField;
}

/**
 * Default variation for Text Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSliceDefault = prismic.SharedSliceVariation<
	'default',
	Simplify<TextSliceDefaultPrimary>,
	never
>;

/**
 * Slice variation for *Text*
 */
type TextSliceVariation = TextSliceDefault;

/**
 * Text Shared Slice
 *
 * - **API ID**: `text`
 * - **Description**: Text
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextSlice = prismic.SharedSlice<'text', TextSliceVariation>;

declare module '@prismicio/client' {
	interface CreateClient {
		(
			repositoryNameOrEndpoint: string,
			options?: prismic.ClientConfig
		): prismic.Client<AllDocumentTypes>;
	}

	interface CreateWriteClient {
		(
			repositoryNameOrEndpoint: string,
			options: prismic.WriteClientConfig
		): prismic.WriteClient<AllDocumentTypes>;
	}

	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}

	namespace Content {
		export type {
			FooterDocument,
			FooterDocumentData,
			GeneralDocument,
			GeneralDocumentData,
			GeneralDocumentDataTestimonialItem,
			GeneralDocumentDataLogosItem,
			HeaderDocument,
			HeaderDocumentData,
			HeaderDocumentDataNavTopItem,
			NewsArticleDocument,
			NewsArticleDocumentData,
			NewsArticleDocumentDataSlicesSlice,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			ProjectDocument,
			ProjectDocumentData,
			ProjectDocumentDataInfosItem,
			ProjectDocumentDataSlicesSlice,
			AllDocumentTypes,
			AccordeonSlice,
			AccordeonSliceDefaultPrimaryItemsItem,
			AccordeonSliceDefaultPrimary,
			AccordeonSliceVariation,
			AccordeonSliceDefault,
			BlankSlice,
			BlankSliceDefaultPrimary,
			BlankSliceVariation,
			BlankSliceDefault,
			CardsSlice,
			CardsSliceDefaultPrimaryItemsItem,
			CardsSliceDefaultPrimary,
			CardsSliceVariation,
			CardsSliceDefault,
			CtaSlice,
			CtaSliceDefaultPrimary,
			CtaSliceVariation,
			CtaSliceDefault,
			ExplanationSlice,
			ExplanationSliceDefaultPrimary,
			ExplanationSliceVariation,
			ExplanationSliceDefault,
			FeaturedProjectsSlice,
			FeaturedProjectsSliceDefaultPrimaryItemsItem,
			FeaturedProjectsSliceDefaultPrimary,
			FeaturedProjectsSliceVariation,
			FeaturedProjectsSliceDefault,
			GallerySlice,
			GallerySliceDefaultPrimaryItemsItem,
			GallerySliceDefaultPrimary,
			GallerySliceVariation,
			GallerySliceDefault,
			GridSlice,
			GridSliceDefaultPrimaryItemsItem,
			GridSliceDefaultPrimary,
			GridSliceVariation,
			GridSliceDefault,
			HeadlineSlice,
			HeadlineSliceDefaultPrimary,
			HeadlineSliceVariation,
			HeadlineSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimaryItemsItem,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			HeroFadeSlice,
			HeroFadeSliceDefaultPrimaryItemsItem,
			HeroFadeSliceDefaultPrimary,
			HeroFadeSliceVariation,
			HeroFadeSliceDefault,
			HighlightsSlice,
			HighlightsSliceDefaultPrimaryItemsItem,
			HighlightsSliceDefaultPrimary,
			HighlightsSliceVariation,
			HighlightsSliceDefault,
			LatestNewsSlice,
			LatestNewsSliceVariation,
			LatestNewsSliceDefault,
			LeftRightSlice,
			LeftRightSliceDefaultPrimary,
			LeftRightSliceVariation,
			LeftRightSliceDefault,
			LeftRightSliderSlice,
			LeftRightSliderSliceDefaultPrimaryItemsItem,
			LeftRightSliderSliceDefaultPrimary,
			LeftRightSliderSliceVariation,
			LeftRightSliderSliceDefault,
			LogosSlice,
			LogosSliceDefaultPrimaryItemsItem,
			LogosSliceDefaultPrimary,
			LogosSliceVariation,
			LogosSliceDefault,
			LogosAnimatedSlice,
			LogosAnimatedSliceDefaultPrimaryItemsItem,
			LogosAnimatedSliceDefaultPrimary,
			LogosAnimatedSliceVariation,
			LogosAnimatedSliceDefault,
			MediaSlice,
			MediaSliceDefaultPrimaryItemsItem,
			MediaSliceDefaultPrimary,
			MediaSliceVariation,
			MediaSliceDefault,
			NewsSlice,
			NewsSliceDefaultPrimaryItemsItem,
			NewsSliceDefaultPrimary,
			NewsSliceVariation,
			NewsSliceDefault,
			PricingSlice,
			PricingSliceDefaultPrimaryItemsItem,
			PricingSliceDefaultPrimary,
			PricingSliceVariation,
			PricingSliceDefault,
			ProjectsSlice,
			ProjectsSliceDefaultPrimaryItemsItem,
			ProjectsSliceDefaultPrimary,
			ProjectsSliceVariation,
			ProjectsSliceDefault,
			SlidingCardsSlice,
			SlidingCardsSliceDefaultPrimaryItemsItem,
			SlidingCardsSliceDefaultPrimary,
			SlidingCardsSliceVariation,
			SlidingCardsSliceDefault,
			TestimonialsSlice,
			TestimonialsSliceDefaultPrimaryItemsItem,
			TestimonialsSliceDefaultPrimary,
			TestimonialsSliceVariation,
			TestimonialsSliceDefault,
			TextSlice,
			TextSliceDefaultPrimary,
			TextSliceVariation,
			TextSliceDefault
		};
	}
}
